---
title: "5 practical tips for better quality management"
date: "2024-08-28"
categories: 'Repost Linkedin'
---

Repost Linkedin : https://www.linkedin.com/posts/yacine-bekka_dataquality-datastrategy-datamanagement-activity-7026086062946963456-FgQ3?utm_source=share&utm_medium=member_desktop

Date originale de publication : Tue, 31 Jan 2023

---

Get your data quality under control with those 5 practical tips ⬇️

➡ Create the business case for hashtag#dataquality

Data quality is not a goal by itself, it is a means to an end. To convince management and ensure their support you need to demonstrate why data quality matters for the company and how it will contribute to the business strategy.

While it can be difficult to show a quantitative ROI at the start, you can always start by a qualitative business case (check out my post on 4 business drivers of data quality here : https://lnkd.in/eYixnUyu)

➡ Start by known pain points

Targeting known pain points is an easy way to create adherence around your data quality management process.

If by the implementation of the process you are able to solve or at least draw a clear view of the root causes, the effort for correction and the business impacts, you will demonstrate the added value of data quality to your company.

➡ Iterate implementation by business terms

If you cannot implement data quality monitoring for all your data (which is often the case), I recommend working by iteration, defining the scope by business terms.

In my experience, it is the best way to scope your iterations based on company priority as business terms are easily relatable and can be linked to known pain points and company strategy

➡ Evaluate criticality and business impact of issues not controls

No one cares about the data quality controls, everybody cares about data quality issues. In most of the cases controls are quite cheap to perform in terms of money and effort.

What is costly is the resolution of data quality issues, it is also where the business impact(s) can be evaluated more precisely

➡ Communicate regularly, show the value

Regular exchange on the current level of data quality, data quality issues and their resolution should be done with data consumers, data producers and business SMEs.

Once you have some, data quality success stories should be shared as much as possible in the company, especially to management. Don’t hesitate to do the “promotion” of data quality management and the added value that it brings.