---
title: "Data VS Information"
date: "2024-08-28"
categories: 'Repost Linkedin'
---

Repost Linkedin : https://www.linkedin.com/posts/yacine-bekka_data-information-debate-activity-7037779968621260800-pVY7?utm_source=share&utm_medium=member_desktop

Date originale de publication : Wed, 01 Mar 2023

---

Most data pros agree on the fact that data is not the same as information.

But are they really that different ?

Let's take a look at commonly used definitions for both concepts :

- Data: Raw, unorganized facts that need to be processed.

- Information: When data is processed, organized, structured or presented in a given context to make it useful.

At first sight those definitions that take roots from the DIKW pyramid, sounds OK but i think there is a caveat…

When most people, even us data pros, talk about data, 90% of the time, we talk about structured data

(the percentage is a wild guess but you get my point)

And if it’s structured it means it must have some context.

Think of a spreadsheet table, you would have the colum name and row number for each “data”

So isn’t it an information then…. ?

That would mean that only unstructured data are *real* data and structured data are information ?

Also, can information originate from something other than data ?

Outside of the industry, people don't know the difference and just want useful data/information.

Who would care about random figures, without any context, that are unorganized and meaningless, right?

So are they really different ? Does it matter that much ?

---
**An interesting exchange in the comment :**

- "My thoughts on information derived from data come from questions asked of the cleaning process. E.g. how do we still keep inputting bad data or data out of limits, where is this data from, who logged it? I think information from other sources is possible, maybe thought experiments i.e., set up the experiment prior to obtaining data, informs the strategy for the collection process. Also, no data in itself informs information. "


- "From the cleaning angle it make more sense to me. I would go for something like information help reducing uncertainty/making decision and data can be or not be an information depending on the question/decision" 